Feat/notice
Hanwoollim-App/Hanwoollim-client pull request #46
Opened 2021-08-31 02:08 UTC by Aperture507

공지사항에서 모든 데이터를 받아온 다음 공지사항 터치 시 네비게이션의 파라미터로 넘겨줍니다

2021-08-31 02:10 UTC, DonghyunKim98 commented on app/components/screens/notice/index.tsx
>  					keyExtractor={(item) => item.id}
- 지금 생각이 든건데 공지사항이 하나도 없을때는 '글이 없습니다' 정도로 Text 를 출력해야할것같습니다.

2021-08-31 02:12 UTC, DonghyunKim98 requested changes

2021-08-31 02:12 UTC, DonghyunKim98 commented on app/components/screens/notice/index.tsx
>  					keyExtractor={(item) => item.id}
- 지금 생각이 든건데 아무 공지가 없을경우 '글이 없습니다' 정도의 텍스트를 보여줘야 할 것 같습니다.

2021-08-31 02:12 UTC, DonghyunKim98 commented on app/components/screens/notice/NoticeDetail.tsx
> +	const { title, date, body, writer } = route.params;
- useRoute 로 관리하면 더 편합니다.

2021-08-31 02:25 UTC, Aperture507 commented on app/components/screens/notice/NoticeDetail.tsx
> +	const { title, date, body, writer } = route.params;
```tsx
function NoticeDetail() {
	const route = useRoute();

	return (
		<ScreenWrapper headerTitle="공지사항">
			<View style={styles.titleBox}>
				<Text style={styles.title}>{route.params.title}</Text>
```
이렇게 해봤는데  {route.params.title} 의 title이 Property 'title' does not exist on type 'object' 라네요..?

2021-08-31 03:13 UTC, DonghyunKim98 requested changes

2021-08-31 03:13 UTC, DonghyunKim98 commented on app/components/screens/notice/NoticeDetail.tsx
> +					<Text style={styles.postText}>{route.params.body}</Text>
- 아까 하던 것 처럼 Destructing 을 이용해 반복되는 코드를 줄입시다.

2021-09-01 01:15 UTC, DonghyunKim98 requested changes

2021-09-01 01:15 UTC, DonghyunKim98 commented on app/components/screens/home/Notice.tsx
> +	}, []);
- useFocusEffect 로 변경

2021-09-01 01:15 UTC, DonghyunKim98 commented on app/components/screens/home/Notice.tsx
> +	console.log(noticeData);
- 콘솔로그 삭제

2021-09-01 01:15 UTC, DonghyunKim98 commented on app/components/screens/home/Notice.tsx
> +		useState<Array<NoticeDetailItemInterface>>();
- 이 부분이 문제입니다. 처음에 아무것도 들어있지 않으니깐 배열의 매소드에 해당하는 map 이 없다고 뜨는거죠

const [noticeData, setNoticeData] = useState<Array<NoticeDetailItemInterface>>(**[]**);

로 고치면 될겁니다.

2021-09-02 01:33 UTC, DonghyunKim98 requested changes

2021-09-02 01:33 UTC, DonghyunKim98 commented on app/components/screens/home/Notice.tsx
> +		}, []),
- 큰 의미는 없지만, getNotice 가 depth array 에 있어야 합니다.

2021-09-02 01:33 UTC, DonghyunKim98 commented on app/components/screens/home/Notice.tsx
> +							{trimmingText(notice.title, 35)}
- 35라는 숫자가 대체 뭘 의미하는지 모릅니다.
- 파일 최상단이나 data 쪽으로 상수화를 해서 옮겨주세요.

2021-09-02 01:33 UTC, DonghyunKim98 commented on app/utils/constant/api/api.ts
> +	});
- 이 부분만 제가 바꿔드릴게요.
- api를 호출할때 parameter 로 get/post 요청할때 필요한 것들만 넘기는것이지 받아오는 데이터를 이용해서 하는 작업에 필요한 요소들까지 넘기라는 뜻이 아니였습니다.

2021-09-02 01:58 UTC, Aperture507 commented on app/components/screens/home/Notice.tsx
> +							{trimmingText(notice.title, 35)}
이 부분은 저도 모르는 부분이었어요 ㅠ 원래 있던 코드여서

2021-09-02 02:03 UTC, DonghyunKim98 commented on app/components/screens/home/Notice.tsx
> +							{trimmingText(notice.title, 35)}
아하 내가 쓴거구나 ㅋㅋㅋㅋㅋㅋㅋ 바꿔줘

2021-09-02 06:40 UTC, Aperture507 commented on app/components/screens/home/Notice.tsx
> +		}, []),
구글링 해도 안나와서 그런데 depth array가 뭔가요..?

2021-09-04 12:51 UTC, merged